### ISSUE TITLE
New sentences

### ISSUE THREAD

**Issue by arjunmenon** [dpressel/arcs-py#1]
Hey
After doing `--train sample-data/train --test sample-data/test`, how do you generate the model and use it for new sentences?

the parse file always require train and test. How do you evaluate it on new sentences then? Usage is not clear.

**Comment by dpressel** [comment]
I do not show an example of parsing a new sentence, but it should be quite simple.  The interface is shown in the main in `parse.py`.  This type of parser requires a projective sentence (no overlapping arcs), but other than that, the only requirement is the words and the part-of-speech (POS).  Just call `parser.run(proj_sentence)`, where `proj_sentence` is a list of tuples of `(word, pos)`.  To serialize and deserialize just use pickle.

Also, keep in mind that while these type of transition parsers are all still used and useful there have been major advances in transition parsing since the paper that this implementation is based on.  This model is far from SoTA these days and for anything serious, you probably should look into more recent literature.
